---
title: "Welcome to my blog"
date: 2019-23-02
---

title: Resume
author: Alexander Rouse
email: Acrouse249@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
 Resume for Alexander Rouse

# social links
twitter_username: your-twitter-handle
github_username:  AlexanderRouse

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
